name: Test

on: [push, pull_request]

jobs:
  test-pytest:
    name: Test pytest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pythonVersion: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pythonVersion }}
      - name: Setup Dependencies
        run: |
          python -m pip install poetry
          python -m poetry install
      - name: Run pytest
        run: python -m poetry run pytest --cov --cov-report=xml:coverage.xml --cov-report=term --cov ./ipfs_cid/
      - name: Upload coverage to Codecov
        if: always()
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.xml
